# Generated by Django 4.0.5 on 2022-07-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine_mgt', '0009_claim_monthly_labour_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='mine_mgt.claim'),
        ),
    ]
