# Generated by Django 4.0.5 on 2022-07-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_mgt', '0010_payment_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('forfeit', 'Forfeited'), ('declined', 'Declined'), ('active', 'Active')], default='pending_approval', max_length=30),
        ),
    ]
