# Generated by Django 4.0.5 on 2022-07-28 04:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mine_mgt', '0011_alter_claim_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
                ('desicion', models.CharField(max_length=50)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('claim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='mine_mgt.claim')),
            ],
        ),
    ]
