# Generated by Django 4.0.5 on 2022-07-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_mgt', '0012_annualinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
