# Generated by Django 4.0.5 on 2022-08-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_mgt', '0013_claim_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
