# Generated by Django 4.0.5 on 2022-07-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='documents',
            new_name='document1',
        ),
        migrations.AddField(
            model_name='profile',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='document3',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
